spring:
  devtools:
    restart:
      log-condition-evaluation-delta: false

 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mymart_admin_db}
  username: ${SPRING_DATASOURCE_USERNAME:root}
  password: ${SPRING_DATASOURCE_PASSWORD:rootuser}

     boot:
    admin:
      client:
        url: http://localhost:1111/   
management:
  endpoints:
    web:
      exposure:
        include: '*'

        app:
  images:
    upload-dir: ${APP_IMAGES_UPLOAD_DIR:C:/Users/amish/Downloads/ecommerce-backend-uploads}
