server:
  port: 8082

spring:
  application:
    name: products-listing-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mymart_product_db
    username: root
    password: rootuser

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  boot:
    admin:
      client:
        url: http://localhost:1111

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

app:
  images:
    upload-dir: C:/Users/amish/Downloads/mymart-product-images
